### ISSUE TITLE
Invalid user name or password.

### ISSUE THREAD

**Issue by eno237** [yahoo/mysql_perf_analyzer#10]
Hi,

where is  "The initial login user and credential are myperf/change."
i've not see the credential file.

http://web01:9092/myperf/signin.htm
Login Failed:
Invalid user name or password.

need ur help.
Thanks

I'm running:
1. OS 
root@web01:/var/www# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty

2. MySQL
Your MySQL connection id is 54
Server version: 5.6.24-72.2 Percona Server (GPL), Release 72.2, Revision 8d0f85b

3. TOOLs
. ij version 10.10
. derby-tools                           10.10.1.1-1                      all          Apache Derby Tools
. openjdk-7-jdk:amd64                   7u79-2.5.5-0ubuntu0.14.04.2      amd64        OpenJDK Development Kit (JDK)
. maven                                 3.0.5-1                          all          Java software project management and comprehension tool
. mailx (GNU Mailutils) 2.99.98

I've created:
. Create a database to store metrics. `CREATE DATABASE my_metrics;`
. Create a MySQL user to access the metrics database `GRANT ALL PRIVILEGES ON my_metrics.* to 'metricsuser'@'localhost' identified by 'metricsuserpassword';`

+--------------------------------------------------------------------------------------------------------------------+
| Grants for metricsuser@localhost                                                                                   |
+--------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'metricsuser'@'localhost' IDENTIFIED BY PASSWORD '*C658BF6B3A41AC470A51510B3240D999D2905845' |
| GRANT ALL PRIVILEGES ON `my_metrics`.* TO 'metricsuser'@'localhost'                                                |
+--------------------------------------------------------------------------------------------------------------------+

NOHUP.out log info:

root@web01:/var/www# tailf nohup.out
 +- {}
 +- {}
 +- {}
 += org.eclipse.jetty.server.session.HashSessionIdManager@3a754386 - STARTED
 |
 +> sun.misc.Launcher$AppClassLoader@6132b73b
     +- file:/var/www/myperfserver-executable-jar-with-dependencies.jar
     +- sun.misc.Launcher$ExtClassLoader@489bb457

Sat May 30 09:19:30 UTC 2015 Server URI: http://localhost:9092/
May 30, 2015 9:20:54 AM com.yahoo.dba.perf.myperf.meta.MetaDB getConnection
SEVERE: Exception
java.sql.SQLNonTransientConnectionException: Connection authentication failure occurred.  Reason: Invalid authentication..
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.newEmbedSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.newSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.checkUserCredentials(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection30.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection40.<init>(Unknown Source)
        at org.apache.derby.jdbc.Driver40.getNewEmbedConnection(Unknown Source)
        at org.apache.derby.jdbc.InternalDriver.connect(Unknown Source)
        at org.apache.derby.jdbc.AutoloadedDriver.connect(Unknown Source)

![snapshot2](https://cloud.githubusercontent.com/assets/12669221/7896730/64ef7f44-06c3-11e5-89ac-c5a6e799af67.png)

**Comment by xrao** [comment]
Initial login user is "myperf", password is "change". This is directly populated into the built in database DerbyDB and the password is hashed there. Better change the password after login.

**Comment by eno237** [comment]
hi Xrao,
This has been done and it works perfectly.
Merci :)

**Comment by xrao** [comment]
Thanks for confirming it works.
