### ISSUE TITLE
Set connect tries as a alert setting

### ISSUE THREAD

**Issue by devalias** [yahoo/mysql_perf_analyzer#18]
please make connect tries configurable, example 3 times before sending a alert.  currently we get a lot of false positive alerts for connect.

**Comment by xrao** [comment]
Which alerts? OFFLINE? Have you checked aborted_connect, aborted_client, max_used_connections metrics? Usually, false OFFLINE alerts are caused by server busy like max connection reached, or server cannot authenticate new connections on time. Since the analyzer has trouble to connect to gather metrics, so it cannot point to the exact issue. I would like to get some idea about what exactly happened. In the meantime, I can add retries to connection attempts.

**Comment by devalias** [comment]
email with this:
MySQL Perf Analyzer Alert - CONNECT_FAILURE

**Comment by xrao** [comment]
OK, that is not an error raised from analyzer connection try failure. The metric is the rate of aborted_connect per minute, meaning your database server has connection failures, possibly from not authorized sources. You can try to change log warning level to see if you can catch them in mysqld.err log.I will make this value configurable and will update you once I am done.

**Comment by xrao** [comment]
Sorry the value is aborted_connect per second. So 15 is really not low.

**Comment by devalias** [comment]
can you make that value adjustable?

**Comment by xrao** [comment]
Updated. You can use Settings page - Alert Settings tab, or Alerts page, to configure the value. However, configuration can only be done at db group or host level, not system wide.

Still, you should check why you have so many failed connection attempts.

**Comment by devalias** [comment]
Thanks Xrao, will test this out.  Yeah not sure what's going on but being able to set this value will help keep the noise down for now.Sent with SolMail App--------- Original Message ---------
From: xrao 
To: yahoo/mysql_perf_analyzer 
Date: Fri Jul 17 10:15:26 EDT 2015
Subject: Re: [mysql_perf_analyzer] Set connect tries as a alert setting (#18)

Updated. You can use Settings page - Alert Settings tab, or Alerts page, to configure the value. However, configuration can only be done at db group or host level, not system wide.

Still, you should check why you have so many failed connection attempts.
