### ISSUE TITLE
Can't store port number larger than 32767 when using built-in derby db

### ISSUE THREAD

**Issue by yoku0825** [yahoo/mysql_perf_analyzer#4]
I inputted my database information in myperf/db.htm, HostName = 192.168.198.214 and Port = 32768.
After submit, logs/myperf.log.0 says

```
May 22, 2015 7:13:34 PM com.yahoo.dba.perf.myperf.metrics.MetricsDbBase upsertDBInfo
INFO: Store or update db [56,192.168.198.214,0,0,32768,information_schema, ssh: false,localhost,null,virtual:false,]
```

That seem ok, but next log says

```
May 22, 2015 7:13:45 PM com.yahoo.dba.perf.myperf.process.MetricScannerRunner tryConnect
WARNING: Failed second attempt to connect to [56,192.168.198.214,1,0,null,information_schema, ssh: false,localhost,null,virtual:false,null]
```

MetricScannerRunner tried to connect port "null".

I confirmed port number which is less equal than 32767, MetricScannerRunner handles port number correctly.

**Comment by xrao** [comment]
Fixed. The port was stored as small int. Instead of change storage types at Derby DB and MySQL, I just added type conversions inside the code. 

Once rebuild, you only need update webapps/myperf.war with the file from myperf/target/myperf.war, then restart the app. After that, make sure go to DB Info page to correct the port number.

**Comment by yoku0825** [comment]
Thank you for your quick response.
I can register my MySQL which uses port 64056.

**Comment by yoku0825** [comment]
When I choice MySQL instead of derby, this issue appears again.

```
May 23, 2015 11:54:51 PM com.yahoo.dba.perf.myperf.springmvc.DbController handleRequestImpl
INFO: action: 3, db [test56,192.168.198.214,0,0,64056,information_schema, ssh: false,localhost,null,virtual:false,user], by user myperf
```

But in DBINFOS

```
mysql> SELECT * FROM DBINFOS\G
*************************** 1. row ***************************
               DBID: 1
             DBTYPE: mysql
        DBGROUPNAME: test56
           INSTANCE: 0
           HOSTNAME: 192.168.198.214
               PORT: -1480
      DATABASE_NAME: information_schema
      USE_SSHTUNNEL: 0
     LOCAL_HOSTNAME: localhost
         LOCAL_PORT: NULL
            CREATED: 2015-05-23 23:32:26
CONNECTION_VERIFIED: 0
       VIRTUAL_HOST: 0
       SNMP_ENABLED: 1
    METRICS_ENABLED: 1
      ALERT_ENABLED: 1
              OWNER: NULL
1 row in set (0.17 sec)

mysql> show create table DBINFOS\G
*************************** 1. row ***************************
       Table: DBINFOS
Create Table: CREATE TABLE `DBINFOS` (
  `DBID` int(11) NOT NULL AUTO_INCREMENT,
  `DBTYPE` varchar(30) DEFAULT NULL,
  `DBGROUPNAME` varchar(30) DEFAULT NULL,
  `INSTANCE` smallint(6) DEFAULT NULL,
  `HOSTNAME` varchar(100) DEFAULT NULL,
  `PORT` smallint(6) DEFAULT NULL,
  `DATABASE_NAME` varchar(60) DEFAULT NULL,
  `USE_SSHTUNNEL` smallint(6) DEFAULT NULL,
  `LOCAL_HOSTNAME` varchar(100) DEFAULT NULL,
  `LOCAL_PORT` smallint(6) DEFAULT NULL,
  `CREATED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CONNECTION_VERIFIED` smallint(6) DEFAULT '0',
  `VIRTUAL_HOST` smallint(6) DEFAULT '0',
  `SNMP_ENABLED` smallint(6) DEFAULT '1',
  `METRICS_ENABLED` smallint(6) DEFAULT '1',
  `ALERT_ENABLED` smallint(6) DEFAULT '1',
  `OWNER` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`DBID`),
  UNIQUE KEY `UK_DBINFOS` (`DBGROUPNAME`,`HOSTNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1
1 row in set (0.02 sec)
```

PORT and LOCAL_PORT are defined as signed smallint.

**Comment by xrao** [comment]
Can you post log? I didn't change storage, but added conversion inside the code.

**Comment by yoku0825** [comment]
Here's whole myperf.log.0.
https://gist.github.com/yoku0825/f8c5f1cfb19b5d5094b7

I found column definitions are SMALLINT (not unsigned) in some files.
https://github.com/yahoo/mysql_perf_analyzer/search?q=PORT+SMALLINT

**Comment by xrao** [comment]
Thanks for the log. The SMALLINT was not the main issue (I should use INT when I started this project), because I missed one conversion. From the log, looks like you didn't check the box "Add DB Credential". Because there was no DB credential was stored for the group, the metrics scanner didn't pick the group.  I didn't set the box to be checked by default, because I frequently add new servers to the same group. Will check in the fix once I have enough tests, along with configurable SNMP community and snmpv3 support.

**Comment by yoku0825** [comment]
Oops.. I'm sorry for taking your time for my mistaken..
Registered with "Add DB Credential" and I confirm that works fine.
Thank you!

**Comment by xrao** [comment]
No problem. Any suggestions and bug findings are welcome.
