### ISSUE TITLE
Can't change SNMP community-name (Feature Request)

### ISSUE THREAD

**Issue by yoku0825** [yahoo/mysql_perf_analyzer#6]
When scanning by SNMPClient, community-name "public" is hard-corded.

https://github.com/yahoo/mysql_perf_analyzer/blob/8ef3ab85e0d2b6cd3196e3441ee5b10c0e36513f/myperf/src/main/java/com/yahoo/dba/perf/myperf/snmp/SNMPClient.java#L306

My environment uses other community-name, not "public", I'd like to configure that.

**Comment by xrao** [comment]
Configurable at site level or host level?

**Comment by xrao** [comment]
Also do you use snmpv3?

**Comment by yoku0825** [comment]
Does "configurable at site level" mean "using same community-name all over instances"?
That is enough for me.

And I don't use v3, using v2c.

Thanks,

**Comment by xrao** [comment]
A tab has been added to Settings page (/myperf/perf.htm?pg=settings). snmpv3 support has been added, too.
1. If none of DB GROUP and DB HOST is specified, the configuration will be applied to all servers.
2. If only DB GROUP is specified, the configuration will be applied to all servers to the group.
3. If a DB GROUP and DB HOST is specified, the configuration will be only applied to the specified server.

**Comment by yoku0825** [comment]
That's cool!
I confirmed that works fine :)

Thank you!
