### ISSUE TITLE
Db details are not properly saved when Test Connection is checked

### ISSUE THREAD

**Issue by nitin88** [yahoo/mysql_perf_analyzer#7]
Hi,

When adding new database and if the test connection is checked in, it adds the server to the list but with incorrect information and when i try to connect, it throws error as I can see db credentials are not stored properly. by removing checkbox its working properly.

**Comment by xrao** [comment]
Please post log. Thanks.

**Comment by xrao** [comment]
OK, I think I figured it out. It is the CASE of DB group name. In general, DB group name will be converted to lower case before storage, but the conversion was missed when password is inserted. Before I can locate all the misses of CASE conversion, please use lower case for db group name.

**Comment by xrao** [comment]
Since no more update, close it.
