### ISSUE TITLE
Please explain what this tool is exactly

### ISSUE THREAD

**Issue by elipoz** [yahoo/mysql_perf_analyzer#8]
There is 0 information on the web about the tool.
Couldn't even find any slides or recording from the Percona conf.
README on github is just about installation.
What exactly is it analyzing? How can I determine if it is even useful?

**Comment by ashwinnellore** [comment]
I'll attached a presentation shortly.

**Comment by ashwinnellore** [comment]
Added the presentation to 'demo'
