### ISSUE TITLE
run normal, access error

### ISSUE THREAD

**Issue by krisjin** [yahoo/mysql_perf_analyzer#9]
## shell run output
 2015-05-29 17:20:08.828:INFO:D:/ProgramFiles/Git/myperf:main: Initializing Spring FrameworkServlet 'dispatcher'
五月 29, 2015 5:20:09 下午 com.yahoo.dba.perf.myperf.meta.KeyTool maskFileReadonly
信息: Execute shell command to change file permission
2015-05-29 17:20:10.001:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2778a6a{D:/ProgramFiles/Git/myperf,file:/E:/myperfserver-server/work/weba
p/,AVAILABLE}{.\webapps\myperf.war}
2015-05-29 17:20:10.017:INFO:oejs.ServerConnector:main: Started ServerConnector@89ce410{HTTP/1.1}{0.0.0.0:9092}
2015-05-29 17:20:10.018:INFO:oejs.Server:main: Started @2194ms
org.eclipse.jetty.server.Server@1f9907ee - STARTED
 += qtp1710951419{STARTED,8<=8<=200,i=3,q=0} - STARTED
 |   +- 10 qtp1710951419-10-selector-ServerConnectorManager@4316d666/0 RUNNABLE @ sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
 |   +- 11 qtp1710951419-11-selector-ServerConnectorManager@4316d666/3 RUNNABLE @ sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
 |   +- 12 qtp1710951419-12-selector-ServerConnectorManager@4316d666/2 RUNNABLE @ sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
 |   +- 13 qtp1710951419-13-selector-ServerConnectorManager@4316d666/1 RUNNABLE @ sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
 |   +- 14 qtp1710951419-14 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 15 qtp1710951419-15 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 16 qtp1710951419-16 TIMED_WAITING @ sun.misc.Unsafe.park(Native Method) IDLE
 |   +- 17 qtp1710951419-17-acceptor-0@7440dada-ServerConnector@89ce410{HTTP/1.1}{0.0.0.0:9092} RUNNABLE @ sun.nio.ch.ServerSocketChannelImpl.accept0(Native Me
hod)
 += ServerConnector@89ce410{HTTP/1.1}{0.0.0.0:9092} - STARTED
 |   +~ org.eclipse.jetty.server.Server@1f9907ee - STARTED
 |   +~ qtp1710951419{STARTED,8<=8<=200,i=3,q=0} - STARTED
 |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@37c039d1 - STARTED
 |   +- org.eclipse.jetty.io.ArrayByteBufferPool@3927dd17
 |   += HttpConnectionFactory@68242e51{HTTP/1.1} - STARTED
 |   |   +- HttpConfiguration@1f5cfd41{32768/8192,8192/8192,https://:0,[]}
 |   += org.eclipse.jetty.server.ServerConnector$ServerConnectorManager@4316d666 - STARTED
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@7381d4e0 keys=0 selected=0 id=0
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.WindowsSelectorImpl@676ef6f3 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@26170092 keys=0 selected=0 id=1
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.WindowsSelectorImpl@30d73d83 keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@3077c82 keys=0 selected=0 id=2
 |   |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |   |   +- sun.nio.ch.WindowsSelectorImpl@4153abdb keys=0
 |   |   +- org.eclipse.jetty.io.SelectorManager$ManagedSelector@5c37d85e keys=0 selected=0 id=3
 |   |       +- org.eclipse.jetty.io.SelectorManager$ManagedSelector.select(SelectorManager.java:596)
 |   |       +- sun.nio.ch.WindowsSelectorImpl@424d4f5e keys=0
 |   +- sun.nio.ch.ServerSocketChannelImpl[/0:0:0:0:0:0:0:0:9092]
 |   +- qtp1710951419-17-acceptor-0@7440dada-ServerConnector@89ce410{HTTP/1.1}{0.0.0.0:9092}
 += o.e.j.w.WebAppContext@2778a6a{D:/ProgramFiles/Git/myperf,file:/E:/myperfserver-server/work/webapp/,AVAILABLE}{.\webapps\myperf.war} - STARTED
 |   += org.eclipse.jetty.server.session.SessionHandler@53268e44 - STARTED
 |   |   += org.eclipse.jetty.server.session.HashSessionManager@3f581b8c - STARTED
 |   |   |   +~ com.yahoo.dba.perf.myperf.springmvc.ResourceSessionListener@8463d02
 |   |   |   += org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@3b4f528c - STARTED
 |   |   |   +~ org.eclipse.jetty.server.session.HashSessionIdManager@54b483bf - STARTED
 |   |   |   +~ org.eclipse.jetty.security.SecurityHandler$1@17359c0b
 |   |   += org.eclipse.jetty.security.ConstraintSecurityHandler@4097a214 - STARTED
 |   |       +- org.eclipse.jetty.security.DefaultAuthenticatorFactory@2311f02d
 |   |       += org.eclipse.jetty.servlet.ServletHandler@6eaf2c57 - STARTED
 |   |       |   += jsp@19c47==org.eclipse.jetty.jsp.JettyJspServlet,0,true - STARTED
 |   |       |   |   +- fork=false
 |   |       |   |   +- logVerbosityLevel=DEBUG
 |   |       |   |   +- keepgenerated=true
 |   |       |   |   +- scratchdir=E:\myperfserver-server\work\jsp
 |   |       |   |   +- xpoweredBy=false
 |   |       |   |   +- compilerSourceVM=1.7
 |   |       |   |   +- compilerTargetVM=1.7
 |   |       |   |   +- com.sun.appserv.jsp.classpath=E:\myperfserver-server\myperfserver-executable-jar-with-dependencies.jar;D:\ProgramFiles\Java\jdk1.7.0_75
jre\lib\ext\access-bridge-64.jar;D:\ProgramFiles\Java\jdk1.7.0_75\jre\lib\ext\dnsns.jar;D:\ProgramFiles\Java\jdk1.7.0_75\jre\lib\ext\jaccess.jar;D:\ProgramFile
\Java\jdk1.7.0_75\jre\lib\ext\localedata.jar;D:\ProgramFiles\Java\jdk1.7.0_75\jre\lib\ext\sunec.jar;D:\ProgramFiles\Java\jdk1.7.0_75\jre\lib\ext\sunjce_provide
.jar;D:\ProgramFiles\Java\jdk1.7.0_75\jre\lib\ext\sunmscapi.jar;D:\ProgramFiles\Java\jdk1.7.0_75\jre\lib\ext\zipfs.jar
 |   |       |   +- [*.jsp]=>jsp
 |   |       |   += org.eclipse.jetty.servlet.ListenerHolder@2e883c86 - STARTED
 |   |       |   += org.eclipse.jetty.servlet.ListenerHolder@723d9947 - STARTED
 |   |       |   += default@5c13d641==org.eclipse.jetty.servlet.DefaultServlet,0,true - STARTED
 |   |       |   |   +- maxCacheSize=256000000
 |   |       |   |   +- etags=false
 |   |       |   |   +- dirAllowed=true
 |   |       |   |   +- gzip=false
 |   |       |   |   +- maxCachedFileSize=200000000
 |   |       |   |   +- redirectWelcome=false
 |   |       |   |   +- acceptRanges=true
 |   |       |   |   +- welcomeServlets=false
 |   |       |   |   +- aliases=false
 |   |       |   |   +- useFileMappedBuffer=true
 |   |       |   |   +- maxCachedFiles=2048
 |   |       |   +- [/]=>default
 |   |       |   +- [*.jsp, *.jspf, *.jspx, *.xsp, *.JSP, *.JSPF, *.JSPX, *.XSP]=>jsp
 |   |       |   += org.eclipse.jetty.servlet.ListenerHolder@2a1a3ee9 - STARTED
 |   |       |   += sitemesh - STARTED
 |   |       |   += GzipFilter - STARTED
 |   |       |   |   +- mimeTypes=application/json
 |   |       |   += dispatcher@b7ba1aa7==org.springframework.web.servlet.DispatcherServlet,1,true - STARTED
 |   |       |   +- [*.jsp]/[]==0=>sitemesh
 |   |       |   +- [*.htm]/[]==0=>sitemesh
 |   |       |   +- [*.html]/[]==0=>GzipFilter
 |   |       |   +- [*.json]=>dispatcher
 |   |       |   +- [*.htm]=>dispatcher
 |   |       |   +- [*.html]=>dispatcher
 |   |       |   +- [*.html/*]=>dispatcher
 |   |       |
 |   |       +> null
 |   |       +> null
 |   |       +> null
 |   |       +> []
 |   |       +> /={TRACE.omission={RoleInfo[],None}, TRACE={RoleInfo,F,C[],None}}
 |   += org.eclipse.jetty.servlet.ErrorPageErrorHandler@21184897 - STARTED
 |   += org.eclipse.jetty.annotations.ServletContainerInitializersStarter@4145c27a - STARTED
 |   |
 |   +> WebAppClassLoader=MySQL Database Performance Tool@500bb303
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/classes/
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/aopalliance-1.0.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/commons-logging-1.1.3.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/derby-10.8.1.2.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/javax.json-1.0.4.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/javax.json-api-1.0.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/jetty-continuation-9.2.7.v20150116.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/jetty-http-9.2.7.v20150116.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/jetty-io-9.2.7.v20150116.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/jetty-servlets-9.2.7.v20150116.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/jetty-util-9.2.7.v20150116.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/jstl-1.2.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/log4j-1.2.9.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/mysql-connector-java-5.1.34.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/sitemesh-2.4.2.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/snmp4j-1.10.1.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/spring-aop-3.2.9.RELEASE.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/spring-beans-3.2.9.RELEASE.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/spring-context-3.2.9.RELEASE.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/spring-core-3.2.9.RELEASE.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/spring-expression-3.2.9.RELEASE.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/spring-web-3.2.9.RELEASE.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/spring-webmvc-3.2.9.RELEASE.jar
 |   |   +- file:/E:/myperfserver-server/work/webapp/WEB-INF/lib/standard-1.1.2.jar
 |   |   +- sun.misc.Launcher$AppClassLoader@1ebdff3b
 |   |       +- file:/E:/myperfserver-server/myperfserver-executable-jar-with-dependencies.jar
 |   |       +- sun.misc.Launcher$ExtClassLoader@4bbf8a41
 |   +> org.eclipse.jetty.containerInitializers=[ContainerInitializer{org.eclipse.jetty.apache.jsp.JettyJasperInitializer,interested=[],applicable=[],annotated
[]}]
 |   +> javax.servlet.context.tempdir=E:\myperfserver-server\work
 |   +> org.apache.catalina.jsp_classpath=E:\myperfserver-server\work\webapp\WEB-INF\classes;E:\myperfserver-server\work\webapp\WEB-INF\lib\aopalliance-1.0.jar
E:\myperfserver-server\work\webapp\WEB-INF\lib\commons-logging-1.1.3.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\derby-10.8.1.2.jar;E:\myperfserver-serv
r\work\webapp\WEB-INF\lib\javax.json-1.0.4.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\javax.json-api-1.0.jar;E:\myperfserver-server\work\webapp\WEB-INF
lib\jetty-continuation-9.2.7.v20150116.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\jetty-http-9.2.7.v20150116.jar;E:\myperfserver-server\work\webapp\WEB
INF\lib\jetty-io-9.2.7.v20150116.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\jetty-servlets-9.2.7.v20150116.jar;E:\myperfserver-server\work\webapp\WEB-I
F\lib\jetty-util-9.2.7.v20150116.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\jstl-1.2.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\log4j-1.2.9.jar
E:\myperfserver-server\work\webapp\WEB-INF\lib\mysql-connector-java-5.1.34.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\sitemesh-2.4.2.jar;E:\myperfserve
-server\work\webapp\WEB-INF\lib\snmp4j-1.10.1.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\spring-aop-3.2.9.RELEASE.jar;E:\myperfserver-server\work\webap
\WEB-INF\lib\spring-beans-3.2.9.RELEASE.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\spring-context-3.2.9.RELEASE.jar;E:\myperfserver-server\work\webapp\
EB-INF\lib\spring-core-3.2.9.RELEASE.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\spring-expression-3.2.9.RELEASE.jar;E:\myperfserver-server\work\webapp\
EB-INF\lib\spring-web-3.2.9.RELEASE.jar;E:\myperfserver-server\work\webapp\WEB-INF\lib\spring-webmvc-3.2.9.RELEASE.jar;E:\myperfserver-server\work\webapp\WEB-I
F\lib\standard-1.1.2.jar
 |   +> org.eclipse.jetty.server.webapp.ContainerIncludeJarPattern=.*/[^/]*servlet-api-[^/]*\.jar$|.*/javax.servlet.jsp.jstl-.*\.jar$|.*/.*taglibs.*\.jar$
 |   +> org.eclipse.jetty.server.Executor=qtp1710951419{STARTED,8<=8<=200,i=3,q=0}
 |   +> org.apache.tomcat.InstanceManager=org.apache.tomcat.SimpleInstanceManager@7b4dafd8
 |   +> org.springframework.web.context.support.ServletContextScope=org.springframework.web.context.support.ServletContextScope@2953cd26
 |   +> org.apache.jasper.compiler.TldCache=org.apache.jasper.compiler.TldCache@3cc18efc
 |   +> org.springframework.web.servlet.FrameworkServlet.CONTEXT.dispatcher=WebApplicationContext for namespace 'dispatcher-servlet': startup date [Fri May 29
7:20:08 CST 2015]; root of context hierarchy
 +- {}
 +- {}
 +- {}
 += org.eclipse.jetty.server.session.HashSessionIdManager@54b483bf - STARTED
 |
 +> sun.misc.Launcher$AppClassLoader@1ebdff3b
     +- file:/E:/myperfserver-server/myperfserver-executable-jar-with-dependencies.jar
     +- sun.misc.Launcher$ExtClassLoader@4bbf8a41

Fri May 29 17:20:10 CST 2015 Server URI: http://localhost:9092/

## access in the browser, reported 404
http://localhost:9092/myperf

**Comment by xrao** [comment]
Just tested (build and run) on windows 7 with JDK 8 and it works. Here is my startup script (start_myperf.cmd): "-c /myperf" is the one defines the top URL path

java -Xms128m -classpath  myperfserver-executable-jar-with-dependencies.jar com.yahoo.dba.tools.myperfserver.App -j . -p 9092 -w myperf.war -k work -c /myperf

**Comment by xrao** [comment]
Since no updates, close it.
